import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { formatTimestamp, formatTimestampValue } from "../src/utils";
import { formatWebSavedTimestamp } from "../src/web-clean-v1/formatting";

const header = readFileSync(new URL("../src/web-clean-v1/WebEntryWorkflowHeader.tsx", import.meta.url), "utf8");
const workspace = readFileSync(new URL("../src/web-clean-v1/WebEntryWorkspace.tsx", import.meta.url), "utf8");
const app = readFileSync(new URL("../src/web-clean-v1/CleanWebApp.tsx", import.meta.url), "utf8");
const desktopHeader = readFileSync(new URL("../src/components/EntryWorkflowHeader.tsx", import.meta.url), "utf8");
const upsTable = readFileSync(new URL("../src/components/UpsTable.tsx", import.meta.url), "utf8");
const airTable = readFileSync(new URL("../src/components/AirTable.tsx", import.meta.url), "utf8");
const dcTable = readFileSync(new URL("../src/components/DcTable.tsx", import.meta.url), "utf8");
const energyCostTable = readFileSync(new URL("../src/components/EnergyCostTable.tsx", import.meta.url), "utf8");
const srinakarinTable = readFileSync(new URL("../src/components/SrinakarinPowerPhaseTable.tsx", import.meta.url), "utf8");
const dashboardStats = readFileSync(new URL("../src/components/DashboardStats.tsx", import.meta.url), "utf8");

assert.equal(formatWebSavedTimestamp("2026-08-13T03:30:00.000Z"), formatTimestamp(new Date("2026-08-13T03:30:00.000Z")));
assert.equal(formatWebSavedTimestamp("legacy saved marker"), "legacy saved marker");
assert.equal(formatWebSavedTimestamp(null), null);
assert.equal(formatTimestampValue("2026-08-13T03:30:00.000Z"), formatTimestamp(new Date("2026-08-13T03:30:00.000Z")));
assert.equal(formatTimestampValue("legacy saved marker"), "legacy saved marker");

assert.match(header, /import EntryWorkflowHeader/);
assert.match(header, /workbookLabel="Production API"/);
assert.match(header, /completion=\{computeCompletion\(draft\)\}/);
assert.match(header, /onSelectMonth: \(month: string, exists: boolean\) => void/);
assert.match(header, /onSelectMonth=\{onSelectMonth\}/);
assert.match(header, /showHealth=\{false\}/);
assert.match(header, /lang: "th" \| "en"/);
assert.match(header, /Historical Data Edit Mode/);
assert.match(header, /โหมดแก้ไขข้อมูลย้อนหลัง/);
assert.match(header, /Return to latest/);
assert.match(desktopHeader, /showHealth\?: boolean/);
assert.match(app, /<WebEntryWorkspace lang=\{lang\} siteName=\{site\.name\}/);
assert.match(workspace, /<StickyEntryToolbar/);
assert.match(workspace, /Save All sends one concurrency-protected Production API update/);
assert.match(workspace, /listMissingFields\(liveDraft\)/);
assert.match(workspace, /onSave\(\{ ups: liveDraft\.ups/);
assert.match(workspace, /onDraftChange=\{\(ups, srinakarinInputs\)/);
assert.match(workspace, /aboveMobileNav/);
assert.match(workspace, /pb-40 md:pb-24/);
assert.match(workspace, /onDirtyChange\?: \(dirty: boolean\) => void/);
assert.match(workspace, /onDirtyChange\?\.\(hasDraftChanges\)/);
assert.match(workspace, /EntryWorkspaceActions/);
assert.match(workspace, /onRegisterActions\?:/);
assert.match(workspace, /pendingHistoricalSave/);
assert.match(workspace, /Confirm Saving Historical Data/);
assert.match(workspace, /requestSectionSave\("air"/);
assert.match(workspace, /onSaveAll=\{\(\) => void requestSaveAll\(\)\}/);
assert.match(header, /formatWebSavedTimestamp\(/);
assert.match(workspace, /formatWebSavedTimestamp\(draft\.lastSavedUps\)/);
assert.match(workspace, /formatWebSavedTimestamp\(draft\.lastSavedAir\)/);
assert.match(workspace, /formatWebSavedTimestamp\(draft\.lastSavedDc\)/);
assert.match(workspace, /formatWebSavedTimestamp\(draft\.lastSavedEnergyCost\)/);
const history = readFileSync(new URL("../src/components/HistoricalExplorer.tsx", import.meta.url), "utf8");
assert.match(history, /formatTimestampValue\(log\.lastSavedAir\)/);
assert.match(history, /timestamp: formatTimestampValue\(log\.lastSavedDc\)/);
assert.match(workspace, /<UpsTable lang=\{lang\}/);
assert.match(workspace, /<AirTable lang=\{lang\}/);
assert.match(workspace, /<DcTable lang=\{lang\}/);
assert.match(workspace, /<EnergyCostTable lang=\{lang\}/);
assert.match(workspace, /<SrinakarinPowerPhaseTable lang=\{lang\}/);
assert.match(workspace, /<DashboardStats lang=\{lang\} log=\{liveDraft\}/);
assert.match(dashboardStats, /lang\?: "th" \| "en"/);
assert.match(dashboardStats, /โหลด UPS รวม/);
assert.match(upsTable, /lang\?: "th" \| "en"/);
assert.match(upsTable, /รายการโหลด UPS/);
assert.match(airTable, /lang\?: "th" \| "en"/);
assert.match(airTable, /การใช้พลังงานเครื่องปรับอากาศ/);
assert.match(dcTable, /lang\?: "th" \| "en"/);
assert.match(dcTable, /รายการแผงจ่ายไฟ DC/);
assert.match(energyCostTable, /lang\?: "th" \| "en"/);
assert.match(energyCostTable, /การใช้พลังงานอาคารและค่าไฟฟ้า/);
assert.match(srinakarinTable, /lang\?: "th" \| "en"/);
assert.match(srinakarinTable, /ข้อมูลเฟส UPS และ PPC ของศรีนครินทร์/);
for (const table of [upsTable, airTable, dcTable, energyCostTable, srinakarinTable]) {
  assert.match(table, /const handleSave = async/);
  assert.match(table, /if \(result === false\) return/);
}
assert.doesNotMatch(workspace, /onSave=\{(?:ups|air|dc|energyCost) => void onSave/);
assert.match(workspace, /saveAll: \(\) => Promise<boolean>/);
assert.match(app, /beforeunload/);
assert.match(app, /event\.key === "s" \|\| event\.key === "S"/);
assert.match(app, /event\.key === "e" \|\| event\.key === "E"/);
assert.match(app, /event\.key === "F5"/);
assert.match(app, /entryActionsRef\.current\?\.saveAll\(\)/);
assert.match(app, /setView\("reports"\)/);
assert.match(app, /event\.key === "z" \|\| event\.key === "Z"/);
assert.match(app, /undoLastEdit\(\)/);
assert.match(app, /querySelectorAll<HTMLInputElement>\("\[id\^='entry-section-'\] input:not\(:disabled\)"\)/);
assert.match(app, /event\.key === "Enter"/);
assert.match(app, /Unsaved Data Entry changes/);
assert.match(app, /onDirtyChange=\{setEntryDirty\}/);
assert.match(app, /onRegisterActions=\{registerEntryActions\}/);
assert.match(app, /const refreshed = await loadHistory\(siteId, \{ force: true, scope: "dashboard" \}\)/);
assert.match(app, /const refreshedDraft = refreshed\.logs\.find\(item => item\.month === month\)/);
assert.match(app, /const blankAir = \{ \.\.\.empty\.air \}/);
assert.doesNotMatch(app, /air: structuredClone\(seed\.air\)/);
assert.match(app, /import \{ currentMonth \} from "\.\.\/utils\/monthUtils"/);
assert.match(app, /const todayMonth = currentMonth/);
assert.match(app, /pendingCreateMonth/);
assert.match(app, /Create Monthly Record/);
assert.match(app, /const confirmCreateMonth = async/);
assert.match(app, /onSelectMonth=\{\(selected, exists\) => void selectMonth\(selected, exists\)\}/);
assert.match(app, /selectMonth\(event\.target\.value, history\.months\.includes\(event\.target\.value\)\)/);
assert.match(app, /onEditMonth=\{selected => \{ setView\("entry"\); void selectMonth\(selected\); window\.scrollTo\(\{ top: 0, behavior: "smooth" \}\); \}\}/);
assert.match(app, /Save &(?:amp;)? Continue/);
assert.match(app, /Discard/);
assert.match(app, /Cancel/);
assert.match(app, /savePendingNavigation/);
assert.match(app, /setViewState/);
assert.match(desktopHeader, /showHealth\?: boolean/);

console.log("web entry workflow: preserves Desktop save/navigation protection and month/completion controls");
