import assert from "node:assert/strict";
import { INITIAL_HISTORY_MONTHS, historyMonthsForScope } from "../server/services/historyScope";
import { readFileSync } from "node:fs";
import { recentMonthsThroughSelected } from "../src/utils/historyWindow";

const months = ["2025-01", "2025-02", "2025-03", "2025-04", "2025-05", "2025-06", "2025-07", "2025-08"];
assert.equal(INITIAL_HISTORY_MONTHS, 6);
assert.deepEqual(historyMonthsForScope(months, "dashboard"), ["2025-03", "2025-04", "2025-05", "2025-06", "2025-07", "2025-08"]);
assert.deepEqual(historyMonthsForScope(months, "full"), months);
assert.deepEqual(historyMonthsForScope(months, "rack"), months);
assert.deepEqual(historyMonthsForScope([], "dashboard"), []);
assert.deepEqual(recentMonthsThroughSelected(months, "2025-06", 6), ["2025-06", "2025-05", "2025-04", "2025-03", "2025-02", "2025-01"]);
assert.deepEqual(recentMonthsThroughSelected([...months, "2026-01", "2026-02"], "2026-02", 6), ["2026-02", "2026-01", "2025-08", "2025-07", "2025-06", "2025-05"]);

const apiService = readFileSync(new URL("../server/services/apiService.ts", import.meta.url), "utf8");
const app = readFileSync(new URL("../src/web-clean-v1/CleanWebApp.tsx", import.meta.url), "utf8");
const reportPreview = readFileSync(new URL("../src/web-clean-v1/WebReportPreview.tsx", import.meta.url), "utf8");
const historicalCharts = readFileSync(new URL("../src/components/HistoricalCharts.tsx", import.meta.url), "utf8");
const historicalExplorer = readFileSync(new URL("../src/components/HistoricalExplorer.tsx", import.meta.url), "utf8");
const rackUnitSummary = readFileSync(new URL("../src/components/rack/RackUnitCapacitySummary.tsx", import.meta.url), "utf8");
const capacityAlerts = readFileSync(new URL("../src/components/rack/CapacityAlerts.tsx", import.meta.url), "utf8");
assert.match(apiService, /historyMonthsForScope/);
assert.match(app, /Unable to load facilities/);
assert.match(app, /setFacilityError\(`Unable to load facilities/);
assert.match(app, /setNotice\(`Unable to load/);
assert.match(app, /initialHistoryLoading/);
assert.match(app, /setInitialHistoryLoading\(false\)/);
assert.match(app, /setFacilityLoading\(false\)/);
assert.match(app, /setHistory\(\{ months: \[\], logs: \[\] \}\)/);
assert.match(app, /const reportAvailableMonths = \[\.\.\.new Set\(\(bootstrap\?\.sites \?\? \[\]\)\.flatMap/);
assert.match(app, /availableMonths=\{reportAvailableMonths\}/);
assert.doesNotMatch(app, /availableMonths=\{history\.months\}/);
assert.match(app, /onYearChange=\{loadHistoricalYear\}/);
assert.match(app, /loadHistory\(siteId, \{ scope: "full" \}\)/);
assert.match(app, /const refreshReports = useCallback/);
assert.match(app, /onRefresh=\{refreshReports\}/);
assert.match(reportPreview, /onRefresh\?: \(\) => Promise<void>/);
assert.match(reportPreview, /Refreshing/);
assert.ok(app.includes("selectedMonth={displayMonth}"), "non-Reports views use the global Selected Reporting Month, clamped to the Global Display Period");

assert.match(app, /dataSourceLabel=\{lang === "th" \? "Production API" : "Source: Production API"\}/);
assert.ok(app.includes("const allFacilitiesCacheRef = useRef(new Map<string, Promise<ExportFacility[]>>());"), "All Facilities exports cache their request payload");
assert.ok(app.includes("includeRack ? loadRack(site.id, selectedMonth) : Promise.resolve(null)"), "All Facilities loader uses the selected reporting month and skips rack requests when not needed");
assert.ok(app.includes("includeImage ? loadReportImage(site.id, selectedMonth) : Promise.resolve(null)"), "All Facilities loader uses the selected reporting month and skips image requests when not needed");
assert.ok(app.includes("exportAllFacilitiesCsv(await loadAll({ includeRack: true, includeImage: false }), buildSiteComparisonReportModel(await loadComparison(), contextMonth))"), "CSV export requests Rack Capacity and Rack Positions data with the cross-site model");
assert.ok(app.includes("exportAllFacilitiesExcel(await loadAll({ includeRack: true, includeImage: false }), buildSiteComparisonReportModel(await loadComparison(), contextMonth))"), "Excel export omits image requests and carries the cross-site model");
assert.ok(app.includes("exportAllFacilitiesHtml(await loadAll({ includeRack: true, includeImage: true }), buildSiteComparisonReportModel(await loadComparison(), contextMonth), contextMonth)"), "HTML export requests report assets with the cross-site model");
assert.ok(app.includes("exportAllFacilitiesPdf(await loadAll({ includeRack: true, includeImage: true }), buildSiteComparisonReportModel(await loadComparison(), contextMonth), contextMonth)"), "PDF export requests report assets with the cross-site model");
assert.ok(app.includes("Site Rack Capacity & Availability Comparison\", icon: Building2"), "site rack comparison has a distinct navigation icon");
assert.ok(app.includes("displayPeriod={globalDisplayPeriodRange}"), "history views are bounded by the Global Display Period, not the Reports Quick Range");
assert.match(historicalCharts, /selectedMonth: string/);
assert.match(historicalCharts, /useState<TrendPeriod>\(6\)/);
assert.match(historicalExplorer, /selectedMonth: string/);
assert.match(historicalExplorer, /useState<HistoryRange>\("6"\)/);
assert.match(rackUnitSummary, /const TREND_MONTHS = 6/);
assert.match(rackUnitSummary, /<LabelList/);
assert.match(rackUnitSummary, /chartMax/);
assert.match(reportPreview, /loadWebRackUnitCapacityImage/);
assert.match(app, /const freshImage = await loadReportImage\(siteId, contextMonth\)/);
assert.match(app, /rackUnitCapacityImageDataUri: image\?\.dataUri/);
assert.match(capacityAlerts, /Zone A, Zone B, Zone C/);
assert.match(capacityAlerts, /scopeLabel\.localeCompare/);

console.log("web-clean-v1 loading: six-month initial window and non-destructive recovery contract passed");
